version: '3'
services: 
  xrayr: 
    image: cmdhim/xrayr:0.7.0
    container_name: HIM
    volumes:
      - ./config.yml:/etc/XrayR/config.yml # 映射配置文件夹
      - ./dns.json:/etc/XrayR/dns.json 
    restart: always
    network_mode: host
